import { Category, Habit, Task } from "./types";
import { getTodayDateString } from "./utils";

export const initialCategories: Category[] = [
  { id: "work", name: "Work & Deep Focus", color: "#3b82f6", icon: "Briefcase" },
  { id: "personal", name: "Personal & Life", color: "#10b981", icon: "User" },
  { id: "health", name: "Health & Fitness", color: "#f59e0b", icon: "Activity" },
  { id: "learning", name: "Learning & Skill", color: "#8b5cf6", icon: "BookOpen" },
  { id: "creative", name: "Side Projects", color: "#ec4899", icon: "Sparkles" },
];

const today = getTodayDateString();

export const initialHabits: Habit[] = [
  {
    id: "habit-1",
    title: "Morning Sunlight & Hydration",
    description: "Drink 500ml water and get 15 min natural light",
    category: "health",
    targetMinutes: 15,
    preferredTime: "07:00",
    frequency: "daily",
    streak: 8,
    completedDates: [today],
    icon: "Sun",
    color: "#f59e0b",
    createdAt: new Date().toISOString(),
  },
  {
    id: "habit-2",
    title: "Read 20 pages (System Design / Books)",
    description: "Daily reading before bedtime or morning quiet time",
    category: "learning",
    targetMinutes: 30,
    preferredTime: "21:30",
    frequency: "daily",
    streak: 14,
    completedDates: [],
    icon: "BookOpen",
    color: "#8b5cf6",
    createdAt: new Date().toISOString(),
  },
  {
    id: "habit-3",
    title: "Workout / Cardio Session",
    description: "Strength training or 5km run",
    category: "health",
    targetMinutes: 45,
    preferredTime: "17:30",
    frequency: "weekdays",
    streak: 4,
    completedDates: [],
    icon: "Dumbbell",
    color: "#10b981",
    createdAt: new Date().toISOString(),
  },
  {
    id: "habit-4",
    title: "Review daily schedule & goals",
    description: "Reflect on accomplishments and plan the next day",
    category: "work",
    targetMinutes: 15,
    preferredTime: "22:15",
    frequency: "daily",
    streak: 21,
    completedDates: [],
    icon: "CheckSquare",
    color: "#3b82f6",
    createdAt: new Date().toISOString(),
  }
];

export const initialTasks: Task[] = [
  // Today's Scheduled Tasks
  {
    id: "task-sched-1",
    title: "Morning Planning & Coffee",
    description: "Review top 3 priorities for the day",
    category: "personal",
    priority: "medium",
    estimatedMinutes: 30,
    completed: true,
    scheduledDate: today,
    startTime: "08:00",
    endTime: "08:30",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-sched-2",
    title: "Architecture Sprint: e-life Scheduler Core",
    description: "Implement drag-to-time timeline and backlog synchronization",
    category: "work",
    priority: "urgent",
    estimatedMinutes: 90,
    completed: false,
    scheduledDate: today,
    startTime: "09:30",
    endTime: "11:00",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-sched-3",
    title: "Team Standup & Sync",
    description: "Daily progress update & roadmap discussion",
    category: "work",
    priority: "high",
    estimatedMinutes: 30,
    completed: false,
    scheduledDate: today,
    startTime: "11:30",
    endTime: "12:00",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-sched-4",
    title: "Healthy Lunch Break",
    description: "Step away from screen & eat healthy meal",
    category: "health",
    priority: "low",
    estimatedMinutes: 60,
    completed: false,
    scheduledDate: today,
    startTime: "12:30",
    endTime: "13:30",
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-sched-5",
    title: "Deep Work: Habit Analytics UI",
    description: "Build streak heatmaps & recurring frequency engine",
    category: "creative",
    priority: "high",
    estimatedMinutes: 75,
    completed: false,
    scheduledDate: today,
    startTime: "14:00",
    endTime: "15:15",
    createdAt: new Date().toISOString(),
  },

  // Backlog (Unscheduled) Tasks
  {
    id: "task-backlog-1",
    title: "Write blog post on Time Blocking & Productivity",
    description: "Draft 1200 words covering daily schedule techniques",
    category: "creative",
    priority: "medium",
    estimatedMinutes: 60,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-backlog-2",
    title: "Optimize Next.js 15 bundle size & cache headers",
    description: "Review lighthouse audit scores and dynamic imports",
    category: "work",
    priority: "high",
    estimatedMinutes: 45,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-backlog-3",
    title: "Organize desktop workspace & cable management",
    description: "Tidy desk setup for cleaner ergonomics",
    category: "personal",
    priority: "low",
    estimatedMinutes: 30,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-backlog-4",
    title: "Finish Next.js App Router Masterclass Course",
    description: "Complete chapter 8: Server Actions and Parallel Routes",
    category: "learning",
    priority: "medium",
    estimatedMinutes: 90,
    completed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "task-backlog-5",
    title: "Prepare monthly budget review",
    description: "Categorize bank statements and expense tracking",
    category: "personal",
    priority: "high",
    estimatedMinutes: 45,
    completed: false,
    createdAt: new Date().toISOString(),
  }
];
